name: Get latest release version
on:
  schedule:
    - cron:  '*/10 * * * *'
  workflow_dispatch:
jobs:
  fetch-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Fetch release version
        id: fetch-release
        run: |
          curl -sL -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/StevenBlack/hosts/releases/latest | \
            jq "{upstream_tag_name:.tag_name,upstream_body:.body,upstream_published_at:.published_at,upstream_url:.html_url}" \
            > .meta-data/latest-upstream-release.json
          RELEASE=`cat .meta-data/latest-upstream-release.json | jq -r .upstream_tag_name`
          echo "::set-output name=upstream_tag_name::$RELEASE"
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo "" > .meta-data/latest-release.json
          git config --global user.name '${{ github.actor }} via Bot'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add .
          git commit -am "StevenBlack/hosts Release ${{ steps.fetch-release.outputs.upstream_tag_name }}"
          git push

