name: Container Image

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    environment: container_image
    env:
      image_name: dns-blacklists
      login_secret: ${{ secrets.GHCR_ACCESS }}

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Container Image
        run: |
          version=`cat .meta-data/latest-release.json | jq -r '.local_tag_name'`
          
          docker build -f ./container/app.Dockerfile -t ${{ env.image_name }} .
          docker tag ${{ env.image_name }} ghcr.io/${{ github.repository }}:$version
          docker tag ${{ env.image_name }} ghcr.io/${{ github.repository }}:latest
          
          s=${{ env.login_secret }}
          echo $s | docker login ghcr.io -u euh2 --password-stdin
          
          docker push ghcr.io/${{ github.repository }}:latest
