name: Tests
on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed

  workflow_dispatch:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: dns-blacklists

jobs:
  test:
    name: Validate Zone Files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v1
      with:
        image: test-zone-files
        tag: ephemeral
        dockerfiles: |
          ./container/tests.Dockerfile
        #build-args: |
        #  some_arg=some_value
    - name: Validate Zone Files
      run: podman run test-zone-files:ephemeral
    - name: Check App Build
      run: podman build . --file container/app.Dockerfile --tag $IMAGE_NAME
     
